site_name: Center for Computational Mathematics
 University of Colorado Denver 
site_url: https://ccm-docs.readthedocs.io/en/latest/ 
repo_url: https://github.com/ccmucdenver/ccm-docs 
edit_uri: edit/main/docs/
site_description: Documentation for computing resources at the CCM
theme:
  name: readthedocs
  highlightjs: true
  features:
    - navigation.instant
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
    - Welcome: index.md
    - Terms and Conditions: TermsandConditions.md
    - Updates:  updates.md
    - Overview: overview.md
    - Clusters Guide: clusters_guide.md
    - Examples: examples.md
    - Accounts: accounts.md
    - Environment Modules: modules.md
    - Globus File Transfer: globus.md
    - Conda and Python: conda.md
    - JupyterHub: jupyterhub.md
    - Remote Desktop: remote_desktop.md
    - Apache Spark: spark.md
    - Alderaan Cluster: alderaan.md
    - Research Storage: storage.md
    - Singularity Containers: singularity.md
    - Local network: local.md
    - External Resources: external.md
    - Facilities, Equipment, and Other Resources: facilities.md
    - How to Edit: pull_request.md
